
import React, { useState } from 'react';
import { Play, Save, Trash2, Database, Terminal, CheckCircle2, AlertCircle, Clock, ChevronRight, ExternalLink, Sparkles, Send, FileCode, History, Star, FolderOpen, Plus, ShieldCheck, Lock, Lightbulb, Wand2 } from 'lucide-react';
import geminiService from '../services/geminiService.ts';

interface ExecutionResult {
  type: 'success' | 'error' | 'data';
  message: string;
  count?: number;
  latency: string;
  timestamp: string;
  data?: any[];
}

const SqlEditor: React.FC<{ onBrowseTable?: (tableName: string) => void }> = ({ onBrowseTable }) => {
  const [query, setQuery] = useState("-- SQL Editor (Read-Only Safe Mode)\n-- SELECT queries are executed within the current RLS context.\n\nSELECT * FROM users LIMIT 10;");
  const [isExecuting, setIsExecuting] = useState(false);
  const [aiPrompt, setAiPrompt] = useState('');
  const [isAiThinking, setIsAiThinking] = useState(false);
  const [aiAnalysis, setAiAnalysis] = useState<{ explanation: string; fix: string } | null>(null);
  const [result, setResult] = useState<ExecutionResult | null>(null);
  const [activeTab, setActiveTab] = useState<'results' | 'messages'>('messages');

  const SCHEMA_CONTEXT = "Tables: users(id, tenant_id, name, email, role, is_online, created_at), followups(id, tenant_id, user_id, subject, status, followup_date), daily_activity(id, tenant_id, user_id, type, location, activity_date)";

  const handleRun = () => {
    if (!query.trim()) return;
    
    const upperQuery = query.toUpperCase();
    const forbidden = ['INSERT', 'UPDATE', 'DELETE', 'DROP', 'TRUNCATE', 'ALTER', 'CREATE'];
    const foundForbidden = forbidden.find(cmd => upperQuery.includes(cmd));

    setIsExecuting(true);
    setResult(null);
    setAiAnalysis(null);

    // Simulate execution
    setTimeout(() => {
        if (foundForbidden) {
            setResult({
                type: 'error',
                message: `SECURITY_REJECT: The SQL Editor is currently in Read-Only mode. Forbidden operation: ${foundForbidden}.`,
                latency: '4ms',
                timestamp: new Date().toLocaleTimeString()
            });
            setActiveTab('messages');
        } else if (query.toLowerCase().includes('wrong_table')) {
            setResult({
                type: 'error',
                message: `ERROR: relation "wrong_table" does not exist.`,
                latency: '12ms',
                timestamp: new Date().toLocaleTimeString()
            });
            setActiveTab('messages');
        } else {
            setResult({
                type: 'data',
                message: 'Query executed successfully.',
                count: 3,
                latency: '34ms',
                timestamp: new Date().toLocaleTimeString(),
                data: [
                    { id: 'u-101', name: 'Bill Gates', email: 'bill@microsoft.com', role: 'member' },
                    { id: 'u-102', name: 'Steve Jobs', email: 'steve@apple.com', role: 'admin' },
                    { id: 'u-103', name: 'Mark Zuckerberg', email: 'mark@meta.com', role: 'developer' }
                ]
            });
            setActiveTab('results');
        }
        setIsExecuting(false);
    }, 600);
  };

  const handleAiGenerate = async () => {
    if (!aiPrompt.trim()) return;
    setIsAiThinking(true);
    try {
        const generatedSql = await geminiService.generateSql(aiPrompt, SCHEMA_CONTEXT);
        setQuery(prev => prev + "\n\n-- AI Generated Query\n" + generatedSql.trim());
        setAiPrompt('');
        addNotification("SQL generated by Nuvabase AI");
    } catch (err) {
        console.error("AI generation failed", err);
    } finally {
        setIsAiThinking(false);
    }
  };

  const handleDebug = async () => {
    if (!result || result.type !== 'error') return;
    setIsAiThinking(true);
    try {
        const debugResponse = await geminiService.debugSql(query, result.message, SCHEMA_CONTEXT);
        const explanation = debugResponse.match(/\[EXPLANATION\](.*?)(\[FIX\]|$)/s)?.[1]?.trim() || "Failed to analyze error.";
        const fix = debugResponse.match(/\[FIX\](.*)/s)?.[1]?.trim() || "";
        setAiAnalysis({ explanation, fix });
    } catch (err) {
        console.error("Debugging failed", err);
    } finally {
        setIsAiThinking(false);
    }
  };

  const applyFix = () => {
    if (aiAnalysis?.fix) {
        setQuery(aiAnalysis.fix);
        setAiAnalysis(null);
        setResult(null);
    }
  };

  // Simple local notification simulation
  const addNotification = (msg: string) => {
    console.log(`[SQL NOTIFY]: ${msg}`);
  };

  return (
    <div className="h-full flex bg-[#161616] animate-fadeIn overflow-hidden">
      <aside className="w-64 border-r border-[#2e2e2e] bg-[#1c1c1c] flex flex-col shrink-0">
        <div className="p-4 border-b border-[#2e2e2e] space-y-4">
           <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-[#3ecf8e]">
              <ShieldCheck size={14} />
              <span className="text-[10px] font-black uppercase tracking-widest">Safe Mode Active</span>
           </div>
           <button 
            onClick={() => { setQuery('-- New Query\nSELECT * FROM '); setAiAnalysis(null); setResult(null); }}
            className="w-full bg-[#2e2e2e] hover:bg-[#333] text-white text-[10px] font-black uppercase tracking-widest py-2.5 rounded-lg transition-all flex items-center justify-center gap-2"
           >
            <Plus size={14} /> New Query
          </button>
        </div>
        <div className="flex-1 overflow-y-auto custom-scrollbar p-4 space-y-6">
            <section>
              <label className="text-[10px] font-black text-[#444] uppercase tracking-widest flex items-center gap-2 mb-3">
                <Star size={12} /> Templates
              </label>
              <div className="space-y-1">
                {[
                    { name: 'Fetch Tenant Users', sql: 'SELECT * FROM users;' },
                    { name: 'Summary Count', sql: 'SELECT count(*), role FROM users GROUP BY role;' },
                    { name: 'Recent Activity', sql: 'SELECT * FROM daily_activity ORDER BY activity_date DESC LIMIT 50;' },
                    { name: 'Trigger Error (Test)', sql: 'SELECT * FROM wrong_table;' }
                ].map((q, i) => (
                  <button 
                    key={i} 
                    onClick={() => setQuery(q.sql)}
                    className="w-full text-left px-3 py-2 rounded-lg text-xs text-[#9b9b9b] hover:text-white hover:bg-[#2e2e2e] transition-all truncate flex items-center gap-2 group"
                  >
                    <FileCode size={12} className="shrink-0 text-[#444] group-hover:text-[#3ecf8e]" />
                    {q.name}
                  </button>
                ))}
              </div>
            </section>
        </div>
      </aside>

      <div className="flex-1 flex flex-col min-w-0 bg-[#0f0f0f]">
        <header className="h-12 border-b border-[#2e2e2e] flex items-center justify-between px-6 bg-[#1c1c1c] shrink-0">
          <div className="flex items-center gap-4">
            <button 
              onClick={handleRun} 
              disabled={isExecuting}
              className={`bg-[#3ecf8e] hover:bg-[#3ecf8e]/90 text-black px-4 py-1.5 rounded-lg text-xs font-bold flex items-center gap-2 transition-all ${isExecuting ? 'opacity-50 cursor-not-allowed' : 'active:scale-95'}`}
            >
              {isExecuting ? <div className="w-3 h-3 border-2 border-black border-t-transparent rounded-full animate-spin"></div> : <Play size={14} fill="currentColor" />}
              {isExecuting ? 'Running...' : 'Run Query'}
            </button>
            <div className="h-4 w-px bg-[#2e2e2e]"></div>
            <div className="flex items-center gap-2 text-[10px] font-black text-[#444] uppercase">
                <Lock size={12} /> Read-Only Enforcement
            </div>
          </div>
          <button className="text-[#9b9b9b] hover:text-white p-2">
              <Save size={16} />
          </button>
        </header>

        <div className="px-6 py-2 bg-[#1c1c1c] border-b border-[#2e2e2e] flex items-center gap-4">
          <Sparkles size={16} className="text-[#3ecf8e]" />
          <input 
              type="text"
              value={aiPrompt}
              onChange={(e) => setAiPrompt(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleAiGenerate()}
              placeholder="Ask AI to write SQL... (e.g. 'Show me all admins sorted by name')"
              className="flex-1 bg-transparent border-none outline-none text-xs text-[#ededed] placeholder:text-[#444]"
          />
          <button 
              onClick={handleAiGenerate}
              disabled={isAiThinking || !aiPrompt.trim()}
              className={`text-[#3ecf8e] p-1.5 rounded hover:bg-[#3ecf8e]/10 transition-all ${isAiThinking ? 'animate-pulse' : ''}`}
          >
              {isAiThinking ? <div className="w-4 h-4 border-2 border-[#3ecf8e] border-t-transparent rounded-full animate-spin" /> : <Send size={14} />}
          </button>
        </div>

        <div className="flex-1 relative overflow-hidden">
          <textarea 
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            className="w-full h-full bg-[#0d0d0d] p-8 font-mono text-sm outline-none resize-none text-[#ededed] selection:bg-[#3ecf8e]/20 leading-relaxed custom-scrollbar"
            spellCheck={false}
          />
        </div>

        <div className="h-80 border-t border-[#2e2e2e] bg-[#161616] flex flex-col">
          <div className="flex border-b border-[#2e2e2e] bg-[#1c1c1c] shrink-0">
            <button 
              onClick={() => setActiveTab('results')}
              className={`px-6 py-2 text-[10px] font-black uppercase tracking-widest transition-all border-b-2 ${activeTab === 'results' ? 'border-[#3ecf8e] text-[#3ecf8e]' : 'border-transparent text-[#444] hover:text-[#9b9b9b]'}`}
            >
              Results ({result?.data?.length || 0})
            </button>
            <button 
              onClick={() => setActiveTab('messages')}
              className={`px-6 py-2 text-[10px] font-black uppercase tracking-widest transition-all border-b-2 ${activeTab === 'messages' ? 'border-[#3ecf8e] text-[#3ecf8e]' : 'border-transparent text-[#444] hover:text-[#9b9b9b]'}`}
            >
              System Messages
            </button>
          </div>

          <div className="flex-1 overflow-y-auto p-0 custom-scrollbar">
            {activeTab === 'results' ? (
              result?.type === 'data' && result.data ? (
                <table className="w-full text-left text-xs border-collapse">
                  <thead className="text-[#444] bg-[#0d0d0d] border-b border-[#2e2e2e] sticky top-0">
                    <tr>
                      {Object.keys(result.data[0]).map(key => (
                        <th key={key} className="px-6 py-3 font-black uppercase tracking-widest">{key}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-[#2e2e2e]">
                    {result.data.map((row, i) => (
                      <tr key={i} className="hover:bg-[#1c1c1c] transition-colors">
                        {Object.values(row).map((val: any, vi) => (
                          <td key={vi} className="px-6 py-3 font-mono text-[#ededed] truncate max-w-xs">{val}</td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              ) : (
                <div className="flex flex-col items-center justify-center h-full text-[#333]">
                  <Database size={40} className="mb-3 opacity-20" />
                  <p className="text-[10px] font-black uppercase tracking-widest">Execute a query to see data</p>
                </div>
              )
            ) : (
              <div className="p-6 font-mono text-[11px] space-y-4">
                {result && (
                  <div className="animate-slideUp">
                    <div className={`flex flex-col gap-4 p-5 rounded-xl border bg-[#0d0d0d] ${result.type === 'error' ? 'border-red-500/20' : 'border-[#2e2e2e]'}`}>
                      <div className="flex items-start gap-4">
                        {result.type === 'error' ? <AlertCircle size={18} className="text-red-500 mt-0.5" /> : <CheckCircle2 size={18} className="text-[#3ecf8e] mt-0.5" />}
                        <div className="space-y-1 flex-1">
                          <p className={`font-bold ${result.type === 'error' ? 'text-red-400' : 'text-white'}`}>{result.message}</p>
                          <div className="flex gap-4 text-[9px] text-[#444] uppercase font-black tracking-widest">
                              <span>Latency: {result.latency}</span>
                              <span>Time: {result.timestamp}</span>
                              {result.count && <span>Rows: {result.count}</span>}
                          </div>
                        </div>
                        {result.type === 'error' && !aiAnalysis && (
                            <button 
                                onClick={handleDebug}
                                disabled={isAiThinking}
                                className="flex items-center gap-2 bg-[#3ecf8e]/10 hover:bg-[#3ecf8e]/20 text-[#3ecf8e] px-3 py-1.5 rounded-lg border border-[#3ecf8e]/20 text-[10px] font-black uppercase transition-all"
                            >
                                {isAiThinking ? <div className="w-3 h-3 border-2 border-[#3ecf8e] border-t-transparent rounded-full animate-spin" /> : <Lightbulb size={12} />}
                                Debug with AI
                            </button>
                        )}
                      </div>

                      {aiAnalysis && (
                          <div className="mt-2 pt-4 border-t border-white/5 space-y-4 animate-fadeIn">
                             <div className="flex gap-3">
                                <Sparkles size={16} className="text-[#3ecf8e] shrink-0" />
                                <div className="space-y-2">
                                    <p className="text-[#9b9b9b] leading-relaxed italic">{aiAnalysis.explanation}</p>
                                    {aiAnalysis.fix && (
                                        <div className="flex flex-col gap-2 mt-4">
                                            <p className="text-[10px] font-black text-[#444] uppercase tracking-widest">Suggested Fix:</p>
                                            <div className="bg-[#1c1c1c] p-3 rounded-lg border border-[#2e2e2e] text-[#3ecf8e] font-mono break-all">
                                                {aiAnalysis.fix}
                                            </div>
                                            <button 
                                                onClick={applyFix}
                                                className="w-fit flex items-center gap-2 bg-[#3ecf8e] hover:bg-[#3ecf8e]/90 text-black px-4 py-2 rounded-lg text-[10px] font-black uppercase tracking-widest transition-all mt-2"
                                            >
                                                <Wand2 size={12} /> Replace with Fix
                                            </button>
                                        </div>
                                    )}
                                </div>
                             </div>
                          </div>
                      )}
                    </div>
                  </div>
                )}
                {!result && (
                  <div className="text-[#333] italic">Ready for execution. Shard us-east-1 connection active.</div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default SqlEditor;
